# Generated by Django 4.2.13 on 2026-04-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True, related_name="unlocks", to="courses.course"
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
